import './globals.css'
import type { Metadata } from 'next'
import { Inter, Montserrat, Unica_One, } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["300", "100", "400", "500", "700", "900"],
  variable: "--font-montserrat",
});
const unica = Unica_One({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-unica",
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body  className={`${montserrat.className} ${unica.variable}`}>{children}</body>
    </html>
  )
}
